export const FETCH_DATA = "FETCH_DATA";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_DICTIONARIES = "RECEIVE_DICCIONARIES";
export const ERROR = "ERROR";
export const SET_DICTIONARY = "SET_DICTIONARY";
